




define(function(require, exports, module) {
module.exports = {
    "list.approved": "我已审的",
    "global.init.data.upload": "上传数据",
    "list.gridTable": "图文",
    "selcolor.close": "关闭",
    "doclist.add": "添加行",
    "resource.period.half.year.first.name": "{0}年上半年",
    "page.comfirmDelete.newVersion": "您确认要执行此删除操作吗?",
    "calendar.prevYear": "上一年",
    "page.last": "末页",
    "login.page.section4.mobilePortal.info": "企业微信，随时处理工作",
    "page.theNext": "下一页",
    "errors.email": "{0} 必须为标准的邮件格式.",
    "login.verifycode.refresh": "点击切换验证码",
    "model.docReaderName": "可阅读者",
    "calendar.nextDay": "后{0}天",
    "sys.config.parameters": "系统通用参数配置",
    "date.weekDay3": "星期三",
    "home.logout.confirm": "该操作将退出系统，是否继续？",
    "calendar.week.shortNames": "日,一,二,三,四,五,六",
    "message.defaultLang": "默认语言",
    "button.add": "新建",
    "login.error.license.restrict": "您使用的蓝凌软件产品注册用户数已超出许可限制，此账号暂时无法登录系统，请联系管理员解决！",
    "date.weekDay6": "星期六",
    "page.thePrev": "上一页",
    "page.row": "条",
    "errors.treeCycle": "{0} 发生循环嵌套",
    "list.kmDoc.my": "我的知识",
    "home.logout.msg.closeWin": "若要注销您当前登录的身份，请关闭浏览器窗口。",
    "login.username": "用户名：",
    "message.yes": "是",
    "operation.more": "更多",
    "portlet.var.date.threeMonths": "三个月内",
    "resource.period.half.year.next.name": "{0}年下半年",
    "selcolor.title": "调色板工具",
    "calendar.begindate": "开始时间",
    "calendar.perDay": "每     日：",
    "date.shortMonthNames": "一月\", \"二月\", \"三月\", \"四月\", \"五月\", \"六月\", \"七月\", \"八月\", \"九月\", \"十月\", \"十一月\", \"十二月",
    "message.closeWindow": "当前页面处于编辑状态，你的数据可能未保存，是否仍要关闭窗口？",
    "button.export.pdf": "导出PDF",
    "list.orderType": "排序",
    "license.address.mismatch": "当前服务器IP地址为：{0}，MAC地址为：{1}，与绑定的jgroups.bind_addr={2}不匹配，请重新绑定地址",
    "login.page.section2.mobile": "移动化",
    "return.noRecord": "很抱歉，未找到符合条件的记录！",
    "errors.number": "{0} 必须为有效数字类型.",
    "dialog.addAll": "全部添加",
    "model.fdName": "名称",
    "date.interval.second": "秒",
    "portlet.fdName": "名称",
    "login.page.section2.integration.info": "聚合所有，清晰定位",
    "button.saveFormData": "暂存",
    "userexception.moduleexpire": "系统模块已到期：",
    "button.reset": "重置",
    "login.page.section4.instantMessaging": "即时通讯",
    "sys.common.moduleInfo.isTemp": "是",
    "ckeditor.ckresize.first": "已经是第一张图片",
    "login.inupt.username": "用户名",
    "button.submit": "提交",
    "SYSROLE_AUDITOR.description": "三员体系中的安全审计权限，负责系统日志的审计",
    "button.deleteall": "批量删除",
    "button.saveadd": "保存并新建",
    "button.search": "搜索",
    "doclist.bottom.tip": "已经移动至最底，请确认",
    "home.travel": "漫游",
    "page.comfirmDelete": "一旦选择了删除，所选记录的相关数据都会被删除，无法恢复！您确认要执行此删除操作吗？",
    "calendar.thisDay": "当天",
    "userexception.overtime": "刷新超时：",
    "resource.period.type.double.month.name": "双月",
    "portlet.rowsize": "文档数",
    "login.page.section2.humanity": "人性化",
    "login.page.section4.instantMessaging.info": "线上线下，随时随地",
    "login.page.section3.mobile": "移动化",
    "portlet.cate": "分类",
    "login.error.username.encrypt": "当前系统已禁用账号明文传输，请使用密文登录。",
    "resource.period.type.quarter.name": "季",
    "login.page.section2.workflow": "流程",
    "page.next": "后页",
    "errors.invalid": "{0} 为非法.",
    "login.error.user.kicked": "您的账号已在别处登录，请重新登录。",
    "resource.period.type.week.name": "周",
    "global.init.export.data": "导入数据",
    "calendar.nextYear": "下一年",
    "SYSROLE_FORMULA.description": "公式定义器执行保存和模拟操作，公式定义器需要单独授",
    "button.close": "关闭",
    "login.error.locked": "当前帐号密码错误超过限定次数，请于{0}分钟后重新登录，或者联系管理员解锁",
    "date.label": "日期",
    "resource.period.week.name": "{0}-{1}-{2}至{3}-{4}-{5}",
    "button.select": "选择",
    "button.print": "打印",
    "model.fdCreateTime": "创建时间",
    "list.operation": "操作",
    "sys.common.viewInfo.foreginKey": "外键关联：",
    "resource.period.year.name": "{0}年",
    "sys.common.moduleInfo.versionCheck": "版本检测（版本：20150721）",
    "model.fdAlterTime": "修改时间",
    "login.page.section4.applicationIntegration.info": "支持企业公共号及应用快速发布",
    "global.init.import.baseData": "导入系统基础数据",
    "date.weekDay5": "星期五",
    "calendar.switch": "切换",
    "calendar.perMonth": "每     月：",
    "sys.common.moduleInfo.orderNum": "序号",
    "common.fileUpLoad.upload": "上传",
    "third.mq.active.module": "ActiveMQ集成",
    "login.page.section2.mobile.info": "拥抱互联，全新体验，事不宜迟",
    "errors.long": "{0} 必须为长整数.",
    "button.zip.upload": "上传",
    "model.fdId": "ID",
    "ckeditor.ckresize.size": "实际大小",
    "errors.dbException": "数据库错误消息：{0}",
    "export.error.notsupport": "此功能暂不支持IE浏览器，请使用chrome浏览器！",
    "errors.time.after": "{0} 不能早于当前时间.",
    "sys.layout.immediately.typesetting": "立即排版",
    "button.addejournal": "投稿",
    "sys.common.moduleInfo.modifyRecord": "修改记录",
    "login.error.highfrequency": "高频登录，请稍后重试。",
    "button.refresh": "刷新",
    "error.userNotFound": "当前用户不存在",
    "login.language": "语　言：",
    "errors.customer": "错误发生在第{0}行，错误信息为：{1}",
    "sys.common.viewInfo.className": "对象名称：",
    "status.publish": "发布",
    "home.hello": "您好！",
    "sys.common.moduleInfo.modifyTime": "修订时间",
    "dialog.locale.winTitle": "请选择场所",
    "list.rowTable": "摘要",
    "button.export.mht": "导出HTML",
    "calendar.perYear": "每     年：",
    "list.columnTable": "列表",
    "service.notAvail.tip": "与服务器连接不通，请联系系统管理员或等会再试。",
    "sys.oas.module": "组织场所同步",
    "listview.build.msg": "false",
    "calendar.today": "今天",
    "page.total": "共",
    "config.app": "应用配置",
    "dialog.requiredSelect": "请从列表中选择后再点击确定！",
    "button.cancelSelect": "取消选定",
    "button.moveup": "上移",
    "sys.layout.segment.space": "段前空格",
    "home.footer.suggestMessage": "建议使用IE8以上浏览器，支持1024×768以上分辨率",
    "date.format.dayMonth": "MM dd",
    "errors.scaleLength": "{0} 小数位必须小于等于 {1}.",
    "list.sort.fdId": "创建时间",
    "date.interval.after": "后",
    "calendar.enddate": "结束时间",
    "status.discard": "废弃",
    "errors.float": "{0} 必须为有效浮点类型.",
    "errors.alpha": "{0} 必须为英文.",
    "list.search": "常用查询",
    "resource.period.type.half.year.name": "半年",
    "third.ftsearch.module": "统一搜索接口",
    "errors.date": "{0} 不是日期类型.",
    "button.syn": "同步",
    "sys.layout.oneKey.immediately": "一键排版",
    "errors.short": "{0} 必须为短整数.",
    "home.help": "在线帮助",
    "button.save": "保存",
    "errors.header.correct": "请您纠正以下错误：",
    "home.logout.confirm.closeWindows": "关闭窗口",
    "dialog.optList": "待选列表",
    "global.nohomePage": "对不起,当前系统没有配置您可访问的主页,请联系系统管理员.",
    "resource.period.month.name": "{0}年{1}月",
    "global.winTitle": "KMSS系统",
    "button.view": "查看",
    "errors.ioException": "输入/输出错误消息: {0}",
    "login.input.code": "验证码",
    "sys.layout.stay.table": "保留表格",
    "errors.footer": "",
    "sys.layout.stay.link": "保留链接",
    "calendar.month.shortNames": "一月, 二月, 三月, 四月, 五月, 六月, 七月, 八月, 九月, 十月, 十一月, 十二月",
    "date.format.date7y": "yy-mm",
    "status.refuse": "驳回",
    "calendar.nextMonth": "下一月",
    "error.noAccessCreateTemplate": "(您没有权限在分类'{0}'下创建模板,请重新选中类别)",
    "error.formModelConvert.unknown": "域模型与Form模型之间的数据转换错误",
    "session.expire.tip": "会话过期，请打开新页面重新登录后再提交本页面。",
    "operation.config": "配置 ",
    "errors.dollar": "{0} 必须为有效的货币格式，例如：100.00.",
    "sys.common.viewInfo.foreginKeyTargetTable": "外键（目标表）",
    "login.error.password.encrypt": "当前系统已禁用密码明文传输，请使用密文登录。",
    "button.create": "添加",
    "doclist.movedown": "下移",
    "errors.range": "{0} 没有在区间 {1} 和 {2}之间.",
    "button.savedraft": "暂存",
    "calendar.selectYear": "点击选择年份",
    "login.page.section2.cloud.info": "低成本，易操作，高效能",
    "home.logout.msg.notCloseBro": "如果不让EKP关闭您的浏览器窗口，请您自行关闭此窗口。",
    "portlet.var.date.unlimited": "不限",
    "sys.common.viewInfo.foreginKeyMainTable": "外键（主表）",
    "login.page.section5.landrayServicePlatform": "微服务平台",
    "portlet.fdDescription": "描述",
    "calendar.subject": "主题",
    "selcolor.code": "代码：",
    "button.back": "返回",
    "login.password": "密　码：",
    "sys.common.moduleInfo.parallelVersion": "平行版本",
    "return.autoClose": "{0}秒后页面自动关闭",
    "ckeditor.ckresize.tip": "已是最后一张图片，自动为您跳转回第一张图片",
    "message.no": "否",
    "date.weekDay0": "星期日",
    "global.init.data.download": "导出设置",
    "date.format.datetime.3y": "yyy-MM-dd HH:mm",
    "global.init.data.on": "开启初始数据导出  ",
    "error.search.keywords.required": "请输入“关键字”再进行搜索或点击高级搜索！",
    "sys.common.viewInfo.type": "类型",
    "sys.common.moduleInfo.isCustom": "是否定制",
    "login.page.footer.info": "Copyright &copy; 2001-{0} 蓝凌软件 版权所有",
    "sys.common.moduleInfo.currentVersion": "当前版本",
    "portlet.list.desc5": "新版主题展现方式",
    "calendar.byMonth": "按月",
    "common.io.exception": "系统输入输出错误。",
    "error.fieldNotFound": "未找到相关的字段",
    "global.init": "初始化",
    "home.mail": "邮件",
    "errors.maxLength.simple": "{0} 超出 {1} 个英文字符限制",
    "calendar.thisWeek": "本周",
    "status.examine": "待审",
    "page.loadingHint": "请稍等！数据正在加载...",
    "global.init.data.download.select": "选择导出数据",
    "model.tempEditorName": "可维护者",
    "doclist.top.tip": "已经移动至最顶，请确认",
    "doclist.copy": "复制行",
    "home.paramConfig": "参数配置",
    "login.error.password.times": "用户名或密码不正确，还有{0}次登录尝试机会",
    "button.update": "提交",
    "portlet.var.date.oneYear": "一年内",
    "login.page.section2.knowledge": "知识",
    "page.loadFailure": "数据加载失败！",
    "sys.common.viewInfo.notNull": "非空",
    "login.page.section4.mobilePortal": "移动门户",
    "calendar.msg.timeFormat.error": "时间格式有误",
    "error.anonymous.noAccess": "该资源匿名用户不允许访问",
    "errors.sensitive.word.warn": "{0}中含有敏感词{1}，请检查",
    "ajaxJS.info.nameIsSame": "名称重复,请重新输入",
    "sys.common.viewInfo.colName": "列名",
    "date.interval.hour": "小时",
    "return.failure": "{0}操作失败！",
    "calendar.byWeek": "按周",
    "page.curPath": "当前路径：",
    "SYSROLE_SYSADMIN.description": "三员体系中的系统管理权限，负责用户录入、系统配置等操作",
    "sys.common.configcacheclear.failure": "清理配置缓存失败，",
    "date.format.datetime.2y": "yy-MM-dd HH:mm",
    "common.file.fileNotFound": "系统找不到指定文件。",
    "home.nav.myJob": "我的工作",
    "error.cannotloadmessage": "无法获取资源：{0}",
    "global.message": "{0}",
    "resource.period.type.other.name": "其它",
    "home.logout.msg.closeAll": "同时关闭已打开的所有IE窗口。",
    "button.copy": "复制",
    "sys.common.moduleInfo.exportModuleVersion": "导出模块版本",
    "model.tempReaderName": "可使用者",
    "common.wait": "系统正在执行您的操作，请稍等...",
    "list.approval": "待我审的",
    "login.page.section5.kkAppDownload": "KK客戶端下载",
    "calendar.nextWeek": "后{0}周",
    "global.init.system": "系统初始化",
    "home.locale": "场所：{0}",
    "home.logout.confirm.reLogin": "重新登录",
    "calendar.perQuarter": "每     季：",
    "calendar.after2day": "后天",
    "home.logout.msg.notClose": "如果您正使用EKP系统，浏览器窗口会记住您当前登录的身份信息。如果不关闭此窗口，后续的从此浏览器访问EKP系统的操作将使用您先前登录的身份和权限进行。",
    "return.noRecord.reason": "可能原因：",
    "subscribe.subject": "您新的订阅内容",
    "list.lever.up": "上一级",
    "license.address.failed": "获取网卡物理地址失败",
    "dialog.delete": "删　除",
    "errors.required": "{0} 不能为空",
    "global.exception": "未定义错误:{0}",
    "model.docAlteror": "修改人",
    "list.queryType": "其他查询",
    "sys.common.moduleInfo.versionSerialNum": "版本序列号",
    "model.fdOrder": "排序号",
    "sys.config.parameters.fdRowSize": "视图默认显示行数",
    "date.format.datetime": "yyyy-MM-dd HH:mm",
    "home.personalSetting.personName": "姓名：",
    "SYSROLE_SECURITY.description": "三员体系中的安全管理权限，负责系统权限配置等",
    "errors.header.vali": "校验错误",
    "sys.common.moduleInfo.versionMsgNotFound": "版本信息没找到，请检查路径是否正确！",
    "return.optSuccess": "您的操作已成功！",
    "button.edit.newVersion": "修改",
    "errors.noRecord": "该文档不存在",
    "SYSROLE_SYSADMIN.name": "系统管理权限",
    "return.title": "您的请求已提交，系统返回如下信息：",
    "page.changeTo": "转到",
    "home.moduleConfig": "应用配置",
    "selcolor.light": "亮度：",
    "date.shortWeekDayNames": "日\", \"一\", \"二\", \"三\", \"四\", \"五\", \"六",
    "date.format.date5y": "MM/dd/yyyy",
    "resource.period.type.month.name": "月",
    "return.optFailure": "操作失败！",
    "home.dept": "部门：{0}",
    "list.manager": "后台配置",
    "status.expire": "过期",
    "calendar.byDay": "按天",
    "calendar.prevWeek": "前{0}周",
    "login.button.home": "设为主页",
    "model.fdCreator": "创建人",
    "return.otherQuery.try": "请尝试其他查询条件",
    "date.format.date4y": "yyyy-MM-dd",
    "errors.minLength": "{0} 不能少于 {1} 字符.",
    "global.init.system.button": "执行",
    "resource.period.double.month.name": "{0}年{1}-{2}双月",
    "page.comfirmDelete.formMapping": "删除映射后有数据的表表名加备份，没有数据的表直接删除，请确认是否要执行删除操作？",
    "errors.integer": "{0} 必须为整数.",
    "dialog.currentValue": "当前值：",
    "button.clear": "清除",
    "config.global": "全局配置",
    "login.page.section2.report": "报表",
    "operation.create": "新建 ",
    "sys.common.moduleInfo.checkInfo": "检测项目文件是否有发生改变",
    "portlet.var.date.oneMonth": "一个月内",
    "calendar.confirm": "确定",
    "errors.datetime": "{0} 不是日期时间类型.",
    "title.option": "操作",
    "home.logoTitle": "返回首页",
    "login.page.section3.scene": "场景化",
    "model.docEditorName": "可编辑者",
    "calendar.year": "年",
    "admin.config.success": "请重启服务器！",
    "calendar.close": "关闭",
    "login.title": "登录系统",
    "SYSROLE_FORMULA.name": "公式定义器执行保存和模拟操作",
    "calendar.choice": "筛选",
    "calendar.perWeek": "每     周：",
    "error.noAccessCreateTemplate.alert": "您没有权限在分类'{0}'下创建模板,请重新选择类别!",
    "page.invalid": "您真的要禁用所选记录吗？",
    "dialog.selList": "已选列表",
    "global.init.export": "导入设置",
    "resource.period.type": "区间类型",
    "date.format.date": "yyyy-MM-dd",
    "login.title.account": "账号登录",
    "config.common.workflow": "通用流程模板",
    "locale.language": "zh-CN",
    "userexception.moduleexpire.info": "你访问的系统功能模块{0}已经到期，请联系管理员！",
    "button.zip.download": "打包下载",
    "calendar.week.names": "星期日,星期一,星期二,星期三,星期四,星期五,星期六",
    "sys.common.moduleInfo.title": "版本信息 ",
    "page.rownum": "页数",
    "login.page.section5.LEWPlatform.info": "为企业提供微信企业号、服务号的统一管理平台。",
    "button.ok": "确定",
    "button.delete": "删除",
    "page.firstOption": "==请选择==",
    "date.format.date.2y": "yy-MM-dd",
    "login.page.section2.cloud": "云端化",
    "resource.period": "区间",
    "SYSROLE_SECURITY.name": "安全管理权限",
    "button.more": "更多>>",
    "dialog.description": "描述：",
    "userexception.overtime.info": "您长时间未操作系统，已离线，请重新登录！",
    "page.noSelect": "您没有选择需要操作的数据",
    "errors.max": "{0} 必须小于或等于 {1}.",
    "date.format.date.3y": "yyy-MM-dd",
    "userexception.overcount.info": "当前系统在线人数已超出许可数，您无法进行登录，请联系管理员或等待其他用户退出后您再登录！",
    "home.nav.myDraft": "草稿箱",
    "page.page": "页",
    "third.emeeting.module": "Exchange会议集成",
    "dialog.deleteAll": "全部删除",
    "login.page.section5.LEWPlatform": "LWE平台",
    "sys.common.viewInfo.manyToManySubTable": "多对多子表",
    "userexception.overcount": "登录异常：",
    "home.personalSetting.loginAreaName": "默认场所：",
    "error.classCanNotNewInstance": "类 {0} 无法被实例化",
    "error.unexpectedRequest": "无效的请求",
    "home.home": "首页",
    "error.constraintViolationException": "违反数据约束错误，请检查数据是否被关联",
    "login.page.section3.mobile.info": "多端应用，全新的移动互联应用体验",
    "calendar.applyDept": "申请部门",
    "errors.byte": "{0} 必须为字节类型（byte）.",
    "home.homeConfig": "主页设置",
    "date.interval.day": "天",
    "button.insert": "增加",
    "login.input.code.err": "请输入验证码",
    "dialog.selectOther": "选择",
    "errors.alphanum": "{0} 必须为英文或数字.",
    "dialog.selectTime": "选择",
    "sys.common.moduleInfo.versionMsg": "版本信息",
    "date.interval.minute": "分钟",
    "global.init.data": "数据初始化",
    "login.title.scan": "扫码登录",
    "calendar.time.pm": "下午",
    "list.create": "我上传的",
    "page.loadedHint": "已经完成数据加载！",
    "calendar.day.name": "{0}月{1}日",
    "calendar.selectMonth": "点击选择月份",
    "home.portalConfig": "版面设置",
    "admin.config.saveConfig": "系统配置",
    "sys.common.moduleInfo.modifyAssociation": "关联修改",
    "global.accessDenied": "您没有权限访问当前的页面,请联系数字化与运维部。",
    "dialog.requiredKeyword": "请输入关键字再进行搜索！",
    "sys.layout.description": "一键排版功能默认会一键清除文章中加粗、带色、下划线、斜体、链接、广告、脚本、样式等干挠因素，且会去掉段尾空格、删除非段落空行等。",
    "errors.time": "{0} 不是时间类型.",
    "global.pageNotFound": "您访问的页面无法找到",
    "calendar.prevDay": "前{0}天",
    "return.noRecord.reason2": "记录为空",
    "sys.common.moduleInfo.componentName": "组件名称",
    "sys.common.viewInfo.module": "模块",
    "errors.unknown": "很抱歉，操作失败！",
    "SYSROLE_AUDITOR.name": "安全审计权限",
    "login.inupt.password": "密码",
    "login.page.section2.integration": "整合化",
    "sys.layout.stay.bold": "保留粗体",
    "error.formModelConvert.propertyMapRequest": "域模型与Form模型之间转换映射表中，属性{0}的映射信息{1}必须配置",
    "login.lang.switch": "您确认切换到{0}版吗？",
    "login.forgot.password": "忘记密码",
    "list.otherOpt": "其他操作",
    "calendar.type.month": "月",
    "login.page.section3.wisdom": "智慧化",
    "button.export": "导出",
    "resource.period.day.name": "{0}-{1}-{2}",
    "error.noportal.error1": "当前用户没有默认门户",
    "login.page.section5.DingDingComponent.info": "对接钉钉，让工作使命必达，一DING到底。",
    "calendar.irregular": "不定期",
    "login.page.section4.applicationIntegration": "应用集成",
    "SYSROLE_ADMIN.name": "系统_所有操作",
    "calendar.month.names": "一月, 二月, 三月, 四月, 五月, 六月, 七月, 八月, 九月, 十月, 十一月, 十二月",
    "portlet.list.desc4": "日历展现方式",
    "SYSROLE_ADMIN.description": "可以在系统中执行任何操作",
    "login.button.favorite": "加入收藏",
    "selcolor.ok": "确定",
    "sys.common.moduleInfo.componentPath": "组件路径",
    "return.refresh": "请注意及时刷新！",
    "errors.url": "{0} 必须为有效的url地址.",
    "calendar.time.am": "上午",
    "dialog.moveDown": "下移",
    "return.systemInfo": "系统提示",
    "common.fileUpLoad.selectFile": "请选择文件",
    "prompt.name": "名称",
    "sys.layout.picture.center": "图片居中",
    "global.service.unavalable": "您访问的服务当前不可用",
    "errors.double": "{0} 必须为双精度类型（带小数点的数字）.",
    "page.prev": "前页",
    "return.noRecord.msg": "请用其它方式查找",
    "userexception.exception.info": "当前登录数据异常或超出有效时间，请重新登录",
    "return.success": "{0}操作成功！",
    "doclist.moveup": "上移",
    "button.import": "导入",
    "home.welcome": "欢迎您",
    "date.format.time": "HH:mm",
    "dialog.selectOrg": "选择",
    "button.movedown": "下移",
    "message.noRecord": "没有找到相关记录！",
    "date.format.yearMonth": "yyyy-MM ",
    "calendar.quarterMonth.names": "第一月,第二月,第三月",
    "portlet.list.desc1": "简单列表展现方式",
    "return.noRecord.reason1": "没有查看权限",
    "calendar.month": "月",
    "error.noportal.error3": "当前页面没有权限访问",
    "login.page.section2.humanity.info": "精心打造专属你的平台",
    "message.logincode": "验证码错误",
    "global.license.info": "产品许可信息",
    "sys.common.viewInfo.description": "描述",
    "date.monthNames": "一月\", \"二月\", \"三月\", \"四月\", \"五月\", \"六月\", \"七月\", \"八月\", \"九月\", \"十月\", \"十一月\", \"十二月",
    "list.alldoc": "全部文档",
    "portlet.list.desc3": "图文展现方式",
    "login.info": "系统提示：",
    "login.page.section5.landrayCloudlet": "蓝凌微云",
    "home.personalSetting": "个人设置",
    "dialog.removeAll": "全部移除",
    "message.config": "基础设置",
    "sys.common.moduleInfo.isTempVersion": "是否临时版本",
    "message.template": "模板设置",
    "login.inupt": "请输入用户名和密码",
    "portlet.var.date.halfAYear": "半年内",
    "sys.common.viewInfo.length": "长度",
    "home.logout.msg.logout": "注销身份：",
    "home.answer": "技术支持",
    "dialog.moveUp": "上移",
    "errors.min": "{0} 必须大于或等于 {1}.",
    "login.page.captial.tip": "大写锁定已打开",
    "portlet.fdModule": "模块",
    "resource.period.type.day.name": "日",
    "date.format.long": "yyyy年MM月dd日 HH:mm:ss",
    "page.first": "首页",
    "dialog.remove": "移　除",
    "date.format.time.sec.2y": "yy-MM-dd HH:mm:ss",
    "error.noValidPhoneNumber": "请输入有效的手机号",
    "button.continue.upload": "继续上传",
    "errors.maxLength": "{0} 不能大于 {1} 英文字符(1个中文字符相当于3个英文字符).",
    "date.weekDay4": "星期四",
    "page.to": "到",
    "button.cancel": "取消",
    "global.init.data.download.export": "打包下载",
    "global.init.data.zip.download": "打包下载",
    "calendar.tomorrow": "明天",
    "button.batchcopy": "批量复制",
    "userexception.exception": "刷新异常：",
    "message.keyword": "关键字",
    "login.page.section3.wisdom.info": "“连接+发展”的知识发现",
    "error.datadict.propertyUndefined": "域模型{0}的属性{1}未定义",
    "errors.time.before": "{0} 不能晚于当前时间.",
    "sys.common.configcacheclear.success": "配置信息对应缓存清理成功。",
    "subscribe.type": "email",
    "page.serial": "序号",
    "doclist.delete": "删除行",
    "calendar.msg.targetNotExisted": "对象不存在或目前不能编辑",
    "home.sysConfig": "系统配置",
    "time.label": "时间",
    "button.edit": "编辑",
    "error.noportal.error2": "当前门户下没有可访问的页面",
    "home.homeAnother": "首页　>　",
    "list.myQuery": "条件选择",
    "page.the": "第",
    "login.page.section3.scene.info": "让“知识+”无处不在",
    "page.state": "状态",
    "button.moreinfo": "详细信息",
    "login.error.password": "用户名或密码不正确",
    "common.fileUpLoad.title": "文件上传",
    "portlet.list.desc2": "可配置表头列表展现方式",
    "login.verifycode": "验证码：",
    "page.rowPerPage": "每页",
    "login.page.section3.assets.info": "积累、传播和应用“组织记忆”",
    "dialog.selectNone": "取消选定",
    "button.confirmAll": "批量目标确认",
    "login.page.section3.assets": "资产化",
    "login.page.section5.landrayCloudlet.info": "免费使用，免安装，关注即可使用。",
    "global.init.data.off": "关闭初始数据导出 ",
    "home.personalSetting.deptName": "部门：",
    "calendar.type.week": "周",
    "login.page.header.loginBtn": "登录",
    "config.sys": "系统配置",
    "button.advancedSearch": "精确搜索",
    "login.page.header.scan": "扫一扫",
    "status.draft": "草稿",
    "login.page.section2.data": "数据",
    "date.weekDay1": "星期一",
    "dialog.locale.treeRoot": "场所",
    "selcolor.base.color": "基色：",
    "error.noValidIDCard": "请输入有效的身份证号",
    "sys.common.moduleInfo.description": "描述",
    "date.format.time.sec": "yyyy-MM-dd HH:mm:ss",
    "dialog.add": "添　加",
    "date.interval.ago": "前",
    "config.baseinfo": "基本信息",
    "date.format.time.msel": "yyyy-MM-dd HH:mm:ss.SSS",
    "message.quickSearch": "快速检索",
    "sys.common.viewInfo.tableName": "表名称",
    "date.weekDayNames": "星期日\", \"星期一\", \"星期二\", \"星期三\", \"星期四\", \"星期五\", \"星期六",
    "resource.period.type.year.name": "年",
    "button.list": "查询",
    "resource.period.quarter.name": "{0}年第{1}季度",
    "error.formModelConvert.property": "域模型与Form模型之间转换属性{0}错误",
    "common.moduleName": "系统通用",
    "date.format.date6y": "dd/MM/yyyy",
    "calendar.prevMonth": "上一月",
    "calendar.shortMonthNames": "1月\", \"2月\", \"3月\", \"4月\", \"5月\", \"6月\", \"7月\", \"8月\", \"9月\", \"10月\", \"11月\", \"12月",
    "error.datadict.displayPropertyUndefined": "域模型{0}的displayProperty属性未配置",
    "table.no": "序号",
    "sys.cache.module": "缓存机制",
    "global.init.system.message": "系统初始化将执行以下动作：",
    "date.weekDay2": "星期二",
    "page.must_be_int": "必须为整数",
    "home.logout": "退出",
    "login.page.section5.DingDingComponent": "钉钉组件",
    "sys.common.moduleInfo.versionIdentity": "版本标识",
    "login.button.submit": "登录"
};
});